### ISSUE TITLE
Does ghostferry have Docker images?

### ISSUE THREAD

**Issue by fighterleslie** [Shopify/ghostferry#221]
Does ghostferry or ghostferry-copydb have official Docker images?

**Comment by shuhaowu** [comment]
No, but it should be relatively easy to build one. Something like:

```
FROM golang:1.14.8-buster AS builder

ARG GHOSTFERRY_REVISION
ENV GHOSTFERRY_REVISION ${GHOSTFERRY_REVISION:-master}

RUN set -xe; \
    cd /tmp; \
    git clone --depth=1 --branch ${GHOSTFERRY_REVISION} https://github.com/Shopify/ghostferry.git; \
    cd ghostferry; \
    make copydb; \
    make sharding

FROM ubuntu:focal

COPY --from=builder /go/bin /app/ghostferry
COPY --from=builder /tmp/ghostferry/webui /app/ghostferry/webui

# Set the pwd so the web UI works
WORKDIR /app/ghostferry
```

Because Ghostferry is very customizable due to its nature as a library and features like HTTP Callback, you can build very elaborate container setups with a lot more features, which is what we've done internally. However, that setup is a bit too custom for our purposes to be open sourced for now.

**Comment by fighterleslie** [comment]
Got it. Thanks.
